[theme]
primaryColor = "#4361ee"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#212529"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false